<?php

namespace Kevin\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * Repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
