# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
# app/config/security.yml
security:

  encoders:
    Kevin\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      id: fos_user.user_provider.username

  firewalls:
    main_login:
      pattern:               ^/login$
      anonymous:             true
    main_register:
      pattern:               ^/register/$
      anonymous:             true
    main:
      pattern:               ^/
      anonymous:             false
      provider:              main
      form_login:
        login_path:          fos_user_security_login
        check_path:          fos_user_security_check
        default_target_path: kevin_accueil
      logout:
        path:                fos_user_security_logout
        target:              kevin_portfolio_homepage
      remember_me:
        secret:              %secret%

  access_control: