<?php

namespace Kevin\PortfolioBundle\Repository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * Repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
