<?php

namespace Kevin\PortfolioBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * Repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
}
