<?php

namespace Kevin\PortfolioBundle\Repository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProfil()
    {
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.studies', 'st')
            ->add('st')
            ->leftJoin('p.experiences', 'e')
            ->add('e')
            ->leftJoin('p.profilSkills', 'ps')
            ->add('ps');
    }
}
