<?php

namespace Kevin\PortfolioBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Kevin\PortfolioBundle\Entity\Profil;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProfils($page)
    {
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.image', 'i')
            ->addSelect('i')
            ->leftJoin('p.studies', 'st')
            ->addSelect('st')
            ->leftJoin('p.experiences', 'e')
            ->addSelect('e')
            ->leftJoin('p.profilSkills', 'ps')
            ->addSelect('ps')
            ->leftJoin('ps.skill', 'sk')
            ->addSelect('sk')
            ->getQuery();

        $query->setFirstResult(($page-1) * Profil::NB_PROFILS_PER_PAGE)
            ->setMaxResults(Profil::NB_PROFILS_PER_PAGE);

        $results = new Paginator($query, true);

        return $results;
    }

    public function getProfil($id)
    {
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.image', 'i')
            ->addSelect('i')
            ->leftJoin('p.studies', 'st')
            ->addSelect('st')
            ->leftJoin('p.experiences', 'e')
            ->addSelect('e')
            ->leftJoin('p.profilSkills', 'ps')
            ->addSelect('ps')
            ->leftJoin('ps.skill', 'sk')
            ->addSelect('sk')
            ->andWhere('p.id = :id')
                ->setParameter('id', $id)
            ->getQuery();

        return $query->getSingleResult();
    }
}
