kevin_portfolio_homepage:
    path:     /
    defaults:
        _controller: KevinPortfolioBundle:Profil:index

kevin_portfolio_add:
    path:     /add
    defaults:
        _controller: KevinPortfolioBundle:Profil:add

kevin_portfolio_edit:
    path:     /edit/{id}
    defaults:
        _controller: KevinPortfolioBundle:Profil:edit
    requirements:
        id: \d+

kevin_portfolio_delete:
    path:     /delete/{id}
    defaults:
        _controller: KevinPortfolioBundle:Profil:delete
    requirements:
        id: \d+

kevin_portfolio_test:
    path:     /test
    defaults:
        _controller: KevinPortfolioBundle:Profil:test

kevin_portfolio_skill_index:
    path:     /backend/skills/{page}
    defaults:
        _controller: KevinPortfolioBundle:Skill:index
        page:        1
    requirements:
        page: \d+

kevin_portfolio_skill_add:
    path:     /backend/skills/add
    defaults:
        _controller: KevinPortfolioBundle:Skill:add

kevin_portfolio_skill_edit:
    path:     /backend/skills/edit/{id}
    defaults:
        _controller: KevinPortfolioBundle:Skill:edit
    requirements:
        id: \d+

kevin_portfolio_skill_delete:
    path:     /backend/skills/delete/{id}
    defaults:
        _controller: KevinPortfolioBundle:Skill:delete
    requirements:
        id: \d+